on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    name: publish documentation
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: nikeee/setup-pandoc@v1
      - name: Build
        run: cd doc; make
        shell: bash
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/output/
